services:
  db:
    container_name: aula_modelagem_dados
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5434:5432
